services:
  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - .:/app  # Monta o código local no contêiner
      # - ./app/.env:/app/.env 
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db

#   db:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: dev-db
#     environment:
#       SA_PASSWORD: "YourStrong!Passw0rd"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "1433:1433"
#     volumes:
#       - sqlserver_data:/var/opt/mssql  # Persistência de dados

# volumes:
#   sqlserver_data:
